import React from 'react';
import { ScrollView, StyleSheet, View } from 'react-native';

import ApodItem from '../components/ApodItem'


export default function ApodListScreen({ navigation }) {
  const datas = [{"date":"2005-02-05","explanation":"Tune your radio telescope to 408MHz (408 million cycles per second) and check out the Radio Sky! In the 1970s large dish antennas at three radio observatories, Jodrell Bank, MPIfR, and Parkes Observatory, were used to do just that - the data were combined to map the entire sky. Near this frequency, cosmic radio waves are generated by high energy electrons spiraling along magnetic fields. In the resulting false color image, the galactic plane runs horizontally through the center, but no stars are visible. Instead, many of the bright sources near the plane are distant pulsars, star forming regions, and supernova remnants, while the grand looping structures are pieces of bubbles blown by local stellar activity. External galaxies like Centaurus A, located above the plane to the right of center, and the LMC (below and right) also shine in the Radio Sky.","hdurl":"https://apod.nasa.gov/apod/image/0502/408_allsky_big.gif","media_type":"image","service_version":"v1","title":"The Radio Sky: Tuned to 408MHz","url":"https://apod.nasa.gov/apod/image/0502/408_allsky.jpg"},{"date":"2004-03-30","explanation":"One of the most spectacular solar sights is a prominence.  A solar prominence is a cloud of solar gas held above the Sun's surface by the Sun's magnetic field.  Last month, NASA's Sun-orbiting SOHO spacecraft imaged an impressively large prominence hovering over the surface, pictured above.  The Earth would easily fit under the hovering curtain of hot gas.  A quiescent prominence typically lasts about a month, and may erupt in a Coronal Mass Ejection (CME) expelling hot gas into the Solar System.  Although somehow related to the Sun's changing magnetic field, the energy mechanism that creates and sustains a Solar prominence is still a topic of research.","hdurl":"https://apod.nasa.gov/apod/image/0403/sunprom2_soho_big.gif","media_type":"image","service_version":"v1","title":"A Prominent Solar Prominence from SOHO","url":"https://apod.nasa.gov/apod/image/0403/sunprom2_soho.jpg"},{"date":"1998-07-30","explanation":"This \"synthetic color\" image swath of the Elysium Volcanic Region of Mars was recorded by Mars Global Surveyor's wide angle camera on July 2. North is up and the sun illuminates the scene from the lower right. Bright clouds hover near the northern most dome-shaped volcano Hecates Tholus. The shield volcano Elysium Mons lies about 250 miles south near the image center, and farther south lies another dome-shaped volcano, Albor Tholus, with a broad summit basin or caldera. Even though Mars is just half the size of planet Earth, it is known for its volcanos - the largest of which dwarf their terrestrial counterparts.","hdurl":"https://apod.nasa.gov/apod/image/9807/elysiumvol_mgs_big.jpg","media_type":"image","service_version":"v1","title":"Volcanos on Mars: Elysium Region","url":"https://apod.nasa.gov/apod/image/9807/elysiumvol_mgs.jpg"}]



  return (
    <View style={styles.container}>
      <ScrollView style={styles.scroller}>
        {datas.map((data, i) => (
          <ApodItem
            key={"apod-"+i}
            data={data} 
            onPress={() => navigation.navigate("Detail", { data }) } />
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#CCC',
  },
  scroller: {
    height: "100%"
  },
});